### ISSUE TITLE
428 error Unexpected end of JSON input while parsing near '... >=0.0.4","uglify-js"'

### ISSUE THREAD

**Issue by tsharma89** [EdgeVerve/oe-cloud-cli#1]
![image](https://user-images.githubusercontent.com/156523/33708009-44961104-db5f-11e7-80da-e43c7edf84ae.png)
[2017-12-07T09_24_39_086Z-debug.log](https://github.com/EdgeVerve/oe-cloud-cli/files/1538503/2017-12-07T09_24_39_086Z-debug.log)

**Comment by pktippa** [comment]
@tsharma89 Thanks for raising issue. Could you please give us more details
1. NodeJS Version
2. NPM Version
3. which npm registry you are pointing to 
4. Which windows version.
